swagger: '2.0'
info:
  version: 1.0.0
  title: Barcode 1C
#host: b1s01dsk2.dsk2.picompany.ru
host: 'localhost:3000'
basePath: /v1
schemes:
- http
consumes:
  - application/json
produces:
  - application/json
paths:
  /ping:
    get:
      description: |
        Return `pong` string.
      responses:
        '200':
          description: Pong
          schema:
            type: object
            properties:
              result:
                type: string
                default: pong
